name: ihc_env
channels:
        - defaults
        - conda-forge
dependencies:
        - python=3.8
        - pip
        - pip:
                - numpy
                - matplotlib
                - tqdm
                - wandb
                - accelerate

        - pytorch::pytorch=1.12.1